<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>PHP my own Framework</title>
    <link rel="stylesheet" type="text/css" href="../../../public/css/style.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous">
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</head>
<body class="container">
<header>
    <h1>Welcome guys!</h1>
</header>

<?php if (isset($this->data['notices']) && !empty($this->data['notices'])): ?>
<div class="notices alert alert-success" role="alert">
    <?= implode('. ', $this->data['notices']); ?>
</div>
<?php endif; ?>

<?php if (isset($this->data['errors']) && !empty($this->data['errors'])): ?>
<div class="errors alert alert-danger" role="alert">
    <?= implode('. ', $this->data['errors']); ?>
</div>
<?php endif; ?>